export const CHANGE_BRAND_NAME = 'CHANGE_BRAND_NAME';
export const CHANGE_DESCRIBE = 'CHANGE_DESCRIBE';
export const CHANGE_OBJECTIVES = 'CHANGE_OBJECTIVES';
export const CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB';
